# image name, used as <image name>:<version tag>
# will be checked to the github container registry
name: bazzite-wifi

# description of the image
description: Custom Bazzite image with baked-in RTL8821CU WiFi drivers for MSI GTX 1650 laptop.

# the base image to build on top of (Bazzite Nvidia for your hardware)
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable

modules:
  - type: default-chroot

  - type: copr
    repo: apuimedo/8821cu

  - type: rpm-ostree
    install:
      - 8821cu

  - type: signing
