# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-wifi
description: Custom Bazzite image with injected Realtek 8821cu Wi-Fi drivers.

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: stable

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/apuimedo/8821cu/repo/fedora-%OS_VERSION%/apuimedo-8821cu-fedora-%OS_VERSION%.repo
    install:
      - rtl8821cu
      - akmod-rtl8821cu
