name: BlueBuild Image Automation
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile OS Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: 'recipes/recipe.yml'
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          prune: true
          build_opts: '--no-sign'
